name: Build and Deploy update-user to EC2 from QA

on:
  push:
    branches:
      - qa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: qa

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/update-user:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/update-user:${{ env.IMAGE_TAG }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy container on EC2 from Docker Hub (qa tag)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF

            if ! command -v docker &> /dev/null; then
              echo "🔧 Instalando Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker \$USER
            else
              echo "✅ Docker ya está instalado."
            fi

            echo "${{ secrets.ENV_FILE }}" > ~/update_user.env

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/update-user:${{ env.IMAGE_TAG }}

            sudo docker rm -f update-user || true

            sudo docker run -d \
              --name update-user \
              --env-file ~/update_user.env \
              -p 3003:3003 \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/update-user:${{ env.IMAGE_TAG }}

          EOF